select ESTADO, LIMITE_DE_CREDITO from tabela_de_clientes;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE_SOMA from tabela_de_clientes group by ESTADO;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes 
GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA), MIN(PRECO_DE_LISTA) FROM tabela_de_produtos GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) <= 80;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA), MIN(PRECO_DE_LISTA) FROM tabela_de_produtos GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) <= 80 AND MAX(PRECO_DE_LISTA) > 5;

# EXERCICIO
select * from notas_fiscais;
select CPF, COUNT(*) from notas_fiscais WHERE YEAR(DATA_VENDA) = 2016 group by CPF having count(*) > 2000;