select EMBALAGEM, MAX(PRECO_DE_LISTA) as MAIOR_PRECO from tabela_de_produtos group by EMBALAGEM;

SELECT X.EMBALAGEM, X.MAIOR_PRECO FROM VW_MAIORES_EMBALAGENS X where X.MAIOR_PRECO >= 10;

SELECT A.NOME_DO_PRODUTO, A.EMBALAGEM, A.PRECO_DE_LISTA, B.MAIOR_PRECO
FROM tabela_de_produtos A inner join VW_MAIORES_EMBALAGENS B
ON A.EMBALAGEM = B.EMBALAGEM;

SELECT A.NOME_DO_PRODUTO, A.EMBALAGEM, A.PRECO_DE_LISTA, B.MAIOR_PRECO, 
((A.PRECO_DE_LISTA / B.MAIOR_PRECO)-1) * 100 AS PERCENTUAL
FROM tabela_de_produtos A inner join VW_MAIORES_EMBALAGENS B
ON A.EMBALAGEM = B.EMBALAGEM;