select TP.SABOR, NF.DATA_VENDA, INF.QUANTIDADE from tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = INF.NUMERO;

# QUANTIDADE VENDIDA POR SABOR ANO 2016
select TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
from tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = INF.NUMERO
WHERE year(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, year(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;


select YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
from tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = INF.NUMERO
WHERE year(NF.DATA_VENDA) = 2016
GROUP BY year(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;


SELECT * FROM 
(select TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
from tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = INF.NUMERO
WHERE year(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, year(NF.DATA_VENDA)) as VENDAS_SABOR
INNER JOIN
(select YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
from tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = INF.NUMERO
WHERE year(NF.DATA_VENDA) = 2016
GROUP BY year(NF.DATA_VENDA)) AS VENDAS_TOTAL
ON VENDAS_SABOR.ANO = VENDAS_TOTAL.ANO;


SELECT VENDAS_SABOR.SABOR, VENDAS_SABOR.ANO, VENDAS_SABOR.QUANTIDADE,
round((VENDAS_SABOR.QUANTIDADE/VENDAS_TOTAL.QUANTIDADE) * 100, 2) AS PARTICIPACAO
 FROM 
(select TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
from tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = INF.NUMERO
WHERE year(NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, year(NF.DATA_VENDA)) as VENDAS_SABOR
INNER JOIN
(select YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
from tabela_de_produtos TP
inner join itens_notas_fiscais INF on TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
inner join notas_fiscais NF on NF.NUMERO = INF.NUMERO
WHERE year(NF.DATA_VENDA) = 2016
GROUP BY year(NF.DATA_VENDA)) AS VENDAS_TOTAL
ON VENDAS_SABOR.ANO = VENDAS_TOTAL.ANO
order by PARTICIPACAO DESC;